In [1]:
import numpy as np
import torch

In [2]:

#Vectorizaiton
def vectorize_sumproducts(v1,v2):
    if len(v1)==len(v2):
        s=sum(np.multiply(v1,v2))
        return s
    else:
        return "The length of two vectors must be the same"
def vectorize_Relu(s):
    s=np.array(s)
    s[s<0]=0
    return s
def vectorize_PrimeRelu(s):
    s=np.array(s)
    s[s<=0]=0
    s[s>0]=1
    return s

In [21]:
print(vectorize_sumproducts([1,3,3,4.5,5],[1,2,3,4,7]))

69.0


In [20]:
l=[[-1,2,3],[3,-4,5]]
print(vectorize_Relu(l))
print(vectorize_PrimeRelu(l))

[[0 2 3]
 [3 0 5]]
[[0 1 1]
 [1 0 1]]


In [28]:
test=np.array([[[1,2,3,4,5,9,6],
                [2,7,9,8],
                [1,5,6,9,7],
                [2,3]],
               
               [[1,2,7],
                [2,6]],
               
               [[3,7,0],
                [5,9,0],
                [1,3,5],
                [4,2,1,8,4,2],
                [7,9]],
               
               [[1,5,8,5],
                [5,2,1,4,2,0]]])
print(test.size)

4


In [22]:
#Slice

def Slice_fixed_point(s,length,startpoint):
    s=np.array(s)
    s_p=[]
    for dim in s:
        s_p.append(np.array([row[startpoint:startpoint+length] for row in dim]))
    return np.array(s_p)

def slice_last_point(s,endpoint):
    s=np.array(s)
    s_p=[]
    for dim in s:
        s_p.append(np.array([row[-endpoint:] for row in dim]))
    return np.array(s_p)
  
def slice_random_point(s,length):
    s=np.array(s)
    row_length=[[len(row) for row in dim] for dim in s]
    min_row=np.min(np.min(row_length))
    r=np.random.randint(min_row,size=1)
    s_p=[]
    for dim in s:
        temp=[]
        for row in dim:
            z=row[int(r):int(r)+length]
            temp.append(np.array(z))
        s_p.append(np.array(temp))
    return np.array(s_p)


In [23]:
print(Slice_fixed_point(test,2,1))

[array([list([2, 3]), list([7, 9]), list([5, 6]), list([3])], dtype=object)
 array([list([2, 7]), list([6])], dtype=object)
 array([list([7, 0]), list([9, 0]), list([3, 5]), list([2, 1]), list([9])],
      dtype=object)
 array([[5, 8],
       [2, 1]])]


In [8]:
print(slice_last_point(test,2))

[array([[9, 6],
       [9, 8],
       [9, 7],
       [2, 3]])
 array([[2, 7],
       [2, 6]])
 array([[7, 0],
       [9, 0],
       [3, 5],
       [4, 2],
       [7, 9]])
 array([[8, 5],
       [2, 0]])]


In [24]:
print(slice_random_point(test,2))

[array([[1, 2],
       [2, 7],
       [1, 5],
       [2, 3]])
 array([[1, 2],
       [2, 6]])
 array([[3, 7],
       [5, 9],
       [1, 3],
       [4, 2],
       [7, 9]])
 array([[1, 5],
       [5, 2]])]


In [10]:
# numpy&torch

def numpy2tensor(s):
    s=np.array(s)
    return torch.from_numpy(s)
    
def tensor2numpy(s):
    s=torch.FloatTensor(s)
    return s.numpy() 
#Tensor Sum-products

def Tensor_Sumproducts(a,b):
    a=torch.FloatTensor(a)
    b=torch.FloatTensor(b)
    return a.dot(b)

#Tensor ReLu and ReLu prime

def Tensor_Relu(a):
    a=torch.FloatTensor(a)
    a[a<0]=0
    return a


def Tensor_Relu_prime(a):
    a=torch.FloatTensor(a)
    a[a<=0]=0
    a[a>0]=1
    return a

In [11]:

print(numpy2tensor(np.array(l)))
print(tensor2numpy(torch.ones(7)))
print(type(tensor2numpy(torch.ones(7))))

tensor([[ 1,  2,  3],
        [ 3, -4,  5]], dtype=torch.int32)
[1. 1. 1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>


In [25]:
a=torch.ones(5)*2
b=torch.FloatTensor([1,2,3,4,5])
print(a)
print(b)
print(Tensor_Sumproducts(a,b))

tensor([2., 2., 2., 2., 2.])
tensor([1., 2., 3., 4., 5.])
tensor(30.)


In [13]:
b[0]=3
print(b)

tensor([3., 2., 3., 4., 5.])


In [27]:
l=[[-1,2,3],[3,-4,5]]
Tensor_Relu_prime(l)

tensor([[0., 1., 1.],
        [1., 0., 1.]])

In [15]:
def pad_pattern_end(test):
    out1=[]
    i=0
    out2=[]
    row_length=[[len(row) for row in dim]for dim in test]
    max_row=np.max(np.max(row_length))
    col_length=[len(dim) for dim in test]
    max_col=np.max(col_length)
    for dim in test:
        temp=[]
        for row in dim:
            row=np.pad(row,(0,max_row-len(row)),'symmetric')
            row=list(row)
            temp.append(row)
        out1.append(temp)
        
    for dim in out1:
        dim=np.pad(dim,((0,max_col-len(dim)),(0,0)),'symmetric')
        dim_p=dim
        out2.append(dim_p)
    return np.array(out2)

In [16]:

a=pad_pattern_end(test)
print(a)

[[[1 2 3 4 5 9 6]
  [2 7 9 8 8 9 7]
  [1 5 6 9 7 7 9]
  [2 3 3 2 2 3 3]
  [2 3 3 2 2 3 3]]

 [[1 2 7 7 2 1 1]
  [2 6 6 2 2 6 6]
  [2 6 6 2 2 6 6]
  [1 2 7 7 2 1 1]
  [1 2 7 7 2 1 1]]

 [[3 7 0 0 7 3 3]
  [5 9 0 0 9 5 5]
  [1 3 5 5 3 1 1]
  [4 2 1 8 4 2 2]
  [7 9 9 7 7 9 9]]

 [[1 5 8 5 5 8 5]
  [5 2 1 4 2 0 0]
  [5 2 1 4 2 0 0]
  [1 5 8 5 5 8 5]
  [1 5 8 5 5 8 5]]]
<class 'numpy.ndarray'>


In [17]:
def pad_constant_central(test,cval):
    out1=[]
    out2=[]
    row_length=[[len(row) for row in dim]for dim in test]
    max_row=np.max(np.max(row_length))
    col_length=[len(dim) for dim in test]
    max_col=np.max(col_length)
    for dim in test:
        temp=[]
        for row in dim:
            if (max_row-len(row))%2==0:
                row=np.pad(row,(int((max_row-len(row))/2),int((max_row-len(row))/2)),
                           'constant',constant_values=cval)
            else:
                row=np.pad(row,(int((max_row-len(row))/2),int((max_row-len(row))/2)+1),
                           'constant',constant_values=cval)
            row=list(row)
            temp.append(row)
        out1.append(temp)

    for dim in out1:
        if (max_col-len(dim))%2==0:
            dim=np.pad(dim,((int((max_col-len(dim))/2),int((max_col-len(dim))/2)),(0,0)),
                       'constant',constant_values=cval)
        else:
            dim=np.pad(dim,((int((max_col-len(dim))/2),int((max_col-len(dim))/2)+1),(0,0)),
                       'constant',constant_values=cval)
        dim_p=dim
        out2.append(dim_p)
        
    return np.array(out2)
    

In [18]:
b=pad_constant_central(test,3)
print(b)

[[[1 2 3 4 5 9 6]
  [3 2 7 9 8 3 3]
  [3 1 5 6 9 7 3]
  [3 3 2 3 3 3 3]
  [3 3 3 3 3 3 3]]

 [[3 3 3 3 3 3 3]
  [3 3 1 2 7 3 3]
  [3 3 2 6 3 3 3]
  [3 3 3 3 3 3 3]
  [3 3 3 3 3 3 3]]

 [[3 3 3 7 0 3 3]
  [3 3 5 9 0 3 3]
  [3 3 1 3 5 3 3]
  [4 2 1 8 4 2 3]
  [3 3 7 9 3 3 3]]

 [[3 3 3 3 3 3 3]
  [3 1 5 8 5 3 3]
  [5 2 1 4 2 0 3]
  [3 3 3 3 3 3 3]
  [3 3 3 3 3 3 3]]]


In [19]:
for dim in range(test.shape[0]):
    test[dim]=np.pad(test[dim],((0,0)),'constant')
print(test[0].shape)

(4,)
